import * as fs from 'fs/promises';
import * as fsSync from 'fs';
import path from 'path';
import type { EdgeType } from './grapher';

export interface CacheEdge {
  from: string;
  to: string;
  type: EdgeType;
}

export interface CacheData {
  version: string;
  timestamp: string;
  root: string;
  entrypoints: string[];
  files: string[];
  edges: CacheEdge[];
  reachable: string[];
  orphans: string[];
}

const CACHE_FILENAME = '.codereap-cache.json';

export function getCachePath(projectRoot: string, customPath?: string): string {
  if (customPath) {
    // If custom path already ends with .json, use as-is; otherwise append .json
    return customPath.endsWith('.json') ? customPath : customPath + '.json';
  }
  return path.join(projectRoot, CACHE_FILENAME);
}

export async function writeCache(
  projectRoot: string,
  data: CacheData,
  customPath?: string
): Promise<string> {
  const cachePath = getCachePath(projectRoot, customPath);
  const jsonString = JSON.stringify(data, null, 2);
  await fs.writeFile(cachePath, jsonString);
  return cachePath;
}

export async function readCache(
  projectRoot: string,
  currentVersion: string,
  customPath?: string
): Promise<CacheData> {
  const cachePath = getCachePath(projectRoot, customPath);

  if (!fsSync.existsSync(cachePath)) {
    throw new CacheNotFoundError(
      `No cache found at ${cachePath}. Run \`codereap\` first to generate the analysis cache.`
    );
  }

  const raw = await fs.readFile(cachePath, 'utf-8');
  const data: CacheData = JSON.parse(raw);

  if (data.version !== currentVersion) {
    throw new CacheVersionMismatchError(
      `Cache was generated by codereap v${data.version}, but you are running v${currentVersion}. ` +
        `Please run \`codereap\` to regenerate the cache.`
    );
  }

  // Validate that the cache root matches the current project root
  const resolvedCacheRoot = path.resolve(data.root);
  const resolvedProjectRoot = path.resolve(projectRoot);
  if (resolvedCacheRoot !== resolvedProjectRoot) {
    throw new CacheRootMismatchError(
      `Cache was generated for "${resolvedCacheRoot}", but you are running against "${resolvedProjectRoot}". ` +
        `Please run \`codereap\` to regenerate the cache.`
    );
  }

  return data;
}

export async function purgeCache(projectRoot: string, customPath?: string): Promise<boolean> {
  const cachePath = getCachePath(projectRoot, customPath);
  if (fsSync.existsSync(cachePath)) {
    await fs.unlink(cachePath);
    return true;
  }
  return false;
}

export class CacheNotFoundError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'CacheNotFoundError';
  }
}

export class CacheVersionMismatchError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'CacheVersionMismatchError';
  }
}

export class CacheRootMismatchError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'CacheRootMismatchError';
  }
}
