import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

export function runCli(args: string[], options: { cwd?: string } = {}) {
  const cliPath = path.resolve(__dirname, '../../bin/codereap.js');
  const result = spawnSync('node', [cliPath, ...args], {
    cwd: options.cwd ?? process.cwd(),
    encoding: 'utf8',
    env: { ...process.env, FORCE_COLOR: '0' },
  });

  const outFlagIndex = args.findIndex((a) => a === '--out');
  let json: unknown = undefined;
  let report: unknown = undefined;
  if (outFlagIndex !== -1) {
    const outBase = args[outFlagIndex + 1] ?? 'codereap-report';
    const jsonPath = path.resolve(options.cwd ?? process.cwd(), `${outBase}.json`);
    if (fs.existsSync(jsonPath)) {
      report = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
      // Support both new wrapped format and legacy flat array format
      if (report && typeof report === 'object' && !Array.isArray(report)) {
        const r = report as any;
        json = r.files || r.directories || [];
      } else {
        json = report;
      }
    }
  }

  // Clean up cache file generated by the run (avoid polluting fixture directories)
  const rootFlagIndex = args.findIndex((a) => a === '--root');
  if (rootFlagIndex !== -1) {
    const rootDir = args[rootFlagIndex + 1];
    if (rootDir) {
      const cachePath = path.resolve(options.cwd ?? process.cwd(), rootDir, '.codereap-cache.json');
      try { fs.unlinkSync(cachePath); } catch {}
    }
  }

  return { stdout: result.stdout ?? '', stderr: result.stderr ?? '', status: result.status, json, report };
}


